import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./_styles/globals.css";
import { Web3Modal } from './_context/web3modal'
import 'react-toastify/dist/ReactToastify.css'
import { ToastContainer } from 'react-toastify'
import { ReduxProvider } from "@/app/_redux/provider";
import Header from "./_ui/header";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      
      {/* <Header/> */}
      <body className={`bg-black ${inter.className}`}>

        <ReduxProvider>

        <Web3Modal>
          <Header/>
          {children}
        </Web3Modal>
        <ToastContainer
              position="bottom-center"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              
            />
        </ReduxProvider>
      </body>
    </html>
  );
}
