import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Web3Modal } from '../context/web3modal'
import { Toaster, toast } from 'sonner'
import { ReduxProvider } from "@/redux/provider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}><ReduxProvider>
        <Web3Modal>{children}</Web3Modal>
        <Toaster />
        </ReduxProvider>
      </body>
    </html>
  );
}
